[general]
log_level=info
drone_id = "AS"

[mavlink]
port=14559
host=0.0.0.0

[nmea_objects]
enabled=true

[server]
port=3000
websocket_enabled=true

[features]
photo_capture=true
adsb_handler=true
database_logging=true



